Restaurant\TablesBundle\Document\MenuItem:
    repositoryClass: Restaurant\TablesBundle\Repository\MenuItemRepository
    fields:
        id:
            id: true
        name:
            type: string
        available:
            type: boolean
        price:
            type: float
