Restaurant\TablesBundle\Document\Order:
  fields:
    id:
      id: true
    date:
      type: date
  embedMany:
    orderItems:
      targetDocument: OrderItem
  referenceOne:
    employee:
      targetDocument: CashBundle\Document\Employee
    table:
      targetDocument: Table
