# src/Restaurant/TablesBundle/Resources/config/doctrine/OrderItem.mongodb.yml
Restaurant\TablesBundle\Document\OrderItem:
    fields:
        id:
            id: true
        observations:
            type: string
        delivered:
            type: boolean
    type: embeddedDocument
    referenceOne:
        menuItem:
            targetDocument: MenuItem
            cascade: all
