# src/Restaurant/TablesBundle/Resources/config/doctrine/Reservation.mongodb.yml
Restaurant\TablesBundle\Document\Reservation:
    repositoryClass: Restaurant\TablesBundle\Repository\ReservationRepository
    fields:
        id:
            id: true
        date:
            type: date
        estimated_time:
            type: timestamp
    referenceMany:
        tables:
            targetDocument: Document\Table
            cascade: all
    referenceOne:
        client:
            targetDocument: CashBundle\Document\Client
            cascade: all
