Restaurant\TablesBundle\Document\Store:
    fields:
        id:
            id: true
        address:
            type: string
    referenceOne:
        manager:
            targetDocument: Restaurant\CashBundle\Document\Employee
            cascade: all