# src/Restaurant/TablesBundle/Resources/config/doctrine/Table.mongodb.yml
Restaurant\TablesBundle\Document\Table:
    repositoryClass: Restaurant\TablesBundle\Repository\TableRepository
    fields:
        id:
            id: true
        number:
            type: int
        available:
            type: boolean
        occupationTime:
            type: date
        capacity:
            type: int
