# src/Restaurant/CashBundle/Resources/config/doctrine/Client.mongodb.yml
Restaurant\CashBundle\Document\Client:
    fields:
        id:
            id: true
        dni:
            type: string
        ruc:
            type: string
        name:
            type: string
        address:
            type: string
