restaurant_auth_login:
    path:     /login
    defaults: { _controller: RestaurantAuthBundle:Security:login }

restaurant_auth_login_check:
    path:     /login_check

restaurant_auth_logout:
    path: /logout

restaurant_auth_User:
    type: rest
    prefix: /api
    resource: "Restaurant\AuthBundle\Controller\UserController"

restaurant_auth_homepage:
    path:     /hello/{name}
    defaults: { _controller: RestaurantAuthBundle:Default:index }
