Restaurant\TablesBundle\Document\Reservation:
    exclusion_policy: ALL
    properties:
        estimatedArrivalTime:
          expose: true
        client:
          expose: true
    relations:
        -
            rel: self
            href:
                route: get_reservation
                parameters:
                    id: expr(object.getId())
                absolute: true
            exclusion:
                groups: [tables]
