Restaurant\TablesBundle\Document\Reservation:
    exclusion:
        groups: [tables]
    relations:
        -
            rel: self
            href:
                route: get_reservation
                parameters:
                    id: expr(object.getId())
                absolute: true
            exclusion:
                groups: [tables]
