Restaurant\AuthBundle\Document\User:
    fields:
        id:
            id: true
        username:
            type: string
        password:
            type: string
        email:
            type: string
        salt:
            type: string
        isActive:
            type: boolean
        roles:
            type: collection
    referenceOne:
        employee:
            targetDocument: \Restaurant\CashBundle\Document\Employee
            cascade: all
